server:
  port: 8980
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jxc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # freemarker模板配置
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
    request-context-attribute: ctx
    settings:
      number_format: 0.##

# MyBatis-Plus配置）
mybatis-plus:
  # 实体类别名包
  type-aliases-package: com.lzj.admin.**.pojo
  # mapper xml文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
 
    map-underscore-to-camel-case: true
    cache-enabled: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    root: info
    # mapper包输出debug
    com.lzj.admin.mapper: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'